- name: Set system hostname
  ansible.builtin.hostname:
    name: "{{ host }}"
- name: Update /etc/hosts with new hostname
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1\s+.*'
    line: "127.0.1.1 {{ host }}"
    state: present
- name: Set timezone
  community.general.timezone:
    name: "{{ tz }}"
  become: true
