- name: Ensure Jellyfin directories exist
  tags: [jellyfin]
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: 1000
    group: 1000
    mode: "0775"
    recurse: yes
  loop:
    - "{{ arr }}/jellyfin"
    - "{{ base_path }}/tv"
    - "{{ base_path }}/movies"
- name: Run Jellyfin container
  tags: [jellyfin]
  community.docker.docker_container:
    name: jellyfin
    image: linuxserver/jellyfin:latest
    restart_policy: unless-stopped
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "America/New_York"
    volumes:
      - "{{ arr }}/jellyfin:/config"
      - "{{ base_path }}/tv:/data/tv"
      - "{{ base_path }}/movies:/data/movies"
    networks:
      - name: "{{ traefik_network }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.jellyfin.entrypoints: "websecure"
      traefik.http.routers.jellyfin.rule: "Host(`play.{{ traefik_domain }}`)"
      traefik.http.routers.jellyfin.tls: "true"
      traefik.http.routers.jellyfin.tls.certresolver: "letsencrypt"
      traefik.http.services.jellyfin.loadbalancer.server.port: "8096"
    recreate: yes
