- name: Ensure Sonarr directories exist
  ansible.builtin.file:
    path: "{{ base_path }}/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - config/sonarr
    - downloads
    - tv
- name: Set ownership for Sonarr config folder
  ansible.builtin.file:
    path: "{{ base_path }}/config/sonarr"
    owner: 1000
    group: 1000
    mode: '0755'
  when: xda_available

- name: Run Sonarr container
  community.docker.docker_container:
    name: sonarr
    image: linuxserver/sonarr:latest
    restart_policy: unless-stopped
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "America/New_York"
    volumes:
      - "{{ base_path }}/config/sonarr:/config"
      - "{{ base_path }}/downloads:/downloads"
      - "{{ base_path }}/tv:/tv"
    networks:
      - name: "{{ traefik_network }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.sonarr.entrypoints: "websecure"
      traefik.http.routers.sonarr.rule: "Host(`sonarr.{{ traefik_domain }}`)"
      traefik.http.routers.sonarr.tls: "true"
      traefik.http.routers.sonarr.tls.certresolver: "letsencrypt"
      traefik.http.services.sonarr.loadbalancer.server.port: "8989"
    recreate: yes  